(setq TEST-SENT '(CHARLOTTE EATS HOT DOGS))
(setq TEST-LEXMEM '(((HOT DOGS)
      (FOOD TYPE (WEENER) AMNT (MULTI))
      ( ))
  ((EATS)
      (EAT AGENT AG1 OBJECT OBJ2)
      ((DM-EXP HUMAN BEF AGENT) 
       (DM-EXP FOOD AFT OBJECT)))
  ((CHARLOTTE)  
       (HUMAN F-NAME (CHARLOTTE))
       ( ))))


(format t "~D~%"
(C-ANALYZER TEST-SENT TEST-LEXMEM))